version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 755
    # hooks:
      # BeforeInstall:
      #   - location: deploy-before.sh
      #     runas: ubuntu
      # AfterInstall:
      #   - location: deploy-after.sh
      #     runas: ubuntu
# //   ApplicationStart:
# //     - location: deploy.sh
# //       runas: ubuntu
